CREATE TABLE PRODUCT.SECURITY.DQ_RUN_STATUS (
    DQ_JOB_ID INT,
    DQ_RUN_STATUS VARCHAR (50),
    EXPECTED_DQ_RUN_COUNT INT,
    ACTUAL_DQ_RUN_COUNT INT,
    ACTUAL_DQ_PASS_COUNT INT,
    ACTUAL_DQ_FAIL_COUNT INT,
    DQ_RUN_TIMESTAMP DATETIME2(3)
);

--DROP TABLE PRODUCT.SECURITY.DQ_RUN_STATUS