CREATE PROCEDURE [DATABASE].[SCHEMA].[DQ_CHECK]
AS
BEGIN
    DECLARE @error_script NVARCHAR(MAX);
    DECLARE @result_script NVARCHAR(MAX);
    DECLARE @DQ_RULE_ID INT;
    DECLARE @DQ_JOB_ID_MAX INT;
    DECLARE @DQ_JOB_ID_NEW INT;
    DECLARE @SUBJECT_AREA NVARCHAR(100);
    DECLARE @DATABASE_NAME NVARCHAR(100);
    DECLARE @SCHEMA_NAME NVARCHAR(100);
    DECLARE @TABLE_NAME NVARCHAR(100);
    DECLARE @COLUMN_NAME NVARCHAR(100);
    DECLARE @COLUMN_SPLIT NVARCHAR(100);
    DECLARE @PRIMARY_KEY_COLUMN NVARCHAR(100);
    DECLARE @PRIMARY_KEY_VALUE NVARCHAR(100);
    DECLARE @RULE_DESCRIPTION NVARCHAR(500);
    DECLARE @RULE_THRESHOLD FLOAT;
    DECLARE @RULE_CATEGORY NVARCHAR(100);
    DECLARE @RULE_SEVERITY NVARCHAR(100);
    DECLARE @RULE_VALIDATION_SCRIPT NVARCHAR(MAX);
    DECLARE @ROW_COUNT INT;

    DECLARE cursor_rule CURSOR FOR
    SELECT DQ_RULE_ID, SUBJECT_AREA, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, PRIMARY_KEY_COLUMN,
           RULE_DESCRIPTION, RULE_THRESHOLD, RULE_CATEGORY, RULE_SEVERITY, RULE_VALIDATION_SCRIPT
    FROM DATABASE.SCHEMA.DQ_RULE
    WHERE DQ_ACTIVE_FG = 1
    ORDER BY DQ_RULE_ID;

    OPEN cursor_rule;
    FETCH NEXT FROM cursor_rule INTO @DQ_RULE_ID, @SUBJECT_AREA, @DATABASE_NAME, @SCHEMA_NAME, @TABLE_NAME, @COLUMN_NAME, @PRIMARY_KEY_COLUMN,
                                       @RULE_DESCRIPTION, @RULE_THRESHOLD, @RULE_CATEGORY, @RULE_SEVERITY, @RULE_VALIDATION_SCRIPT;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Splitting primary key column
        SET @PRIMARY_KEY_SPLIT1 = LEFT(@PRIMARY_KEY_COLUMN, CHARINDEX(',', @PRIMARY_KEY_COLUMN) - 1);
        SET @PRIMARY_KEY_SPLIT2 = RIGHT(@PRIMARY_KEY_COLUMN, LEN(@PRIMARY_KEY_COLUMN) - CHARINDEX(',', @PRIMARY_KEY_COLUMN));

        -- Constructing error script
        SET @error_script = 'INSERT INTO DATABASE.SCHEMA.DQ_ERROR (PRIMARY_KEY_NAME, PRIMARY_KEY_VALUE, DO_RULE_ID, DQ_JOB_ID, SUBJECT_AREA, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, COLUMN_VALUE, DO_RESULT, RULE_SEVERITY, RULE_DESCRIPTION, AUDIT_TIMESTAMP, PIT_FLAG)
                             SELECT ''' + @PRIMARY_KEY_SPLIT1 + ''' AS PRIMARY_KEY_NAME, ' + @PRIMARY_KEY_SPLIT2 + ' AS PRIMARY_KEY_VALUE, ' + CAST(@DQ_RULE_ID AS NVARCHAR(10)) + ' AS DO_RULE_ID, ' + CAST(@DO_JOB_ID_NEW AS NVARCHAR(10)) + ' AS DQ_JOB_ID, ''' + @SUBJECT_AREA + ''' AS SUBJECT_AREA, ''' + @DATABASE_NAME + ''' AS DATABASE_NAME, ''' + @SCHEMA_NAME + ''' AS SCHEMA_NAME, ''' + @TABLE_NAME + ''' AS TABLE_NAME, ''' + @COLUMN_NAME + ''' AS COLUMN_NAME, CONCAT('''', '''') AS COLUMN_VALUE, ''FAIL'' AS DO_RESULT, ''' + @RULE_SEVERITY + ''' AS RULE_SEVERITY, ''' + @RULE_DESCRIPTION + ''' AS RULE_DESCRIPTION, CURRENT_TIMESTAMP AS AUDIT_TIMESTAMP
                             FROM ' + @DATABASE_NAME + '.' + @SCHEMA_NAME + '.' + @TABLE_NAME + '
                             WHERE 1=1 AND ' + @RULE_VALIDATION_SCRIPT + ';';

        -- Constructing result script
        SET @result_script = 'INSERT INTO DATABASE.SCHEMA.DQ_RESULT (DO_RULE_ID, DO_JOB_ID, SUBJECT_AREA, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, DQ_RESULT, RULE_SEVERITY, RULE_DESCRIPTION, RULE_THRESHOLD, COUNT_OF_FAILED, COUNT_OF_PASSED, PCT_OF_FAILED, PCT_OF_PASSED, AUDIT_TIMESTAMP)
                              SELECT ' + CAST(@DQ_RULE_ID AS NVARCHAR(10)) + ' AS DO_RULE_ID, ' + CAST(@DO_JOB_ID_NEW AS NVARCHAR(10)) + ' AS DO_JOB_ID, ''' + @SUBJECT_AREA + ''' AS SUBJECT_AREA, ''' + @DATABASE_NAME + ''' AS DATABASE_NAME, ''' + @SCHEMA_NAME + ''' AS SCHEMA_NAME, ''' + @TABLE_NAME + ''' AS TABLE_NAME, ''' + @COLUMN_NAME + ''' AS COLUMN_NAME,
                                     CASE
                                        WHEN ' + CAST(@RULE_THRESHOLD AS NVARCHAR(100)) + ' <= ROUND((SUM(CASE WHEN ' + @RULE_VALIDATION_SCRIPT + ' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) THEN ''BELOW THRESHOLD''
                                        WHEN SUM(CASE WHEN ' + @RULE_VALIDATION_SCRIPT + ' THEN 1 ELSE 0 END) > 0 THEN ''FAIL''
                                        ELSE ''PASS''
                                     END AS DQ_RESULT,
                                     ''' + @RULE_SEVERITY + ''' AS RULE_SEVERITY, ''' + @RULE_DESCRIPTION + ''' AS RULE_DESCRIPTION, ' + CAST(@RULE_THRESHOLD AS NVARCHAR(100)) + ' AS RULE_THRESHOLD,
                                     COALESCE(SUM(CASE WHEN ' + @RULE_VALIDATION_SCRIPT + ' THEN 1 ELSE 0 END), 0) AS COUNT_OF_FAILED,
                                     COALESCE(SUM(CASE WHEN ' + @RULE_VALIDATION_SCRIPT + ' THEN 0 ELSE 1 END), 0) AS COUNT_OF_PASSED,
                                     COALESCE(ROUND((SUM(CASE WHEN ' + @RULE_VALIDATION_SCRIPT + ' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2), 0) AS PCT_OF_FAILED,
                                     COALESCE(ROUND((SUM(CASE WHEN ' + @RULE_VALIDATION_SCRIPT + ' THEN 0 ELSE 1 END) / COUNT(*)) * 100, 2), 0) AS PCT_OF_PASSED,
                                     CURRENT_TIMESTAMP AS AUDIT_TIMESTAMP
                              FROM ' + @DATABASE_NAME + '.' + @SCHEMA_NAME + '.' + @TABLE_NAME + ';';

        -- Execute error_script and result_script
        EXECUTE sp_executesql @error_script;
        EXECUTE sp_executesql @result_script;

        FETCH NEXT FROM cursor_rule INTO @DQ_RULE_ID, @SUBJECT_AREA, @DATABASE_NAME, @SCHEMA_NAME, @TABLE_NAME, @COLUMN_NAME, @PRIMARY_KEY_COLUMN,
                                           @RULE_DESCRIPTION, @RULE_THRESHOLD, @RULE_CATEGORY, @RULE_SEVERITY, @RULE_VALIDATION_SCRIPT;
    END;

    CLOSE cursor_rule;
    DEALLOCATE cursor_rule;
END;
